<script setup>
import { Head, router } from '@inertiajs/vue3';
import DashboardLayout from '@/Layouts/DashboardLayout.vue';
const props = defineProps({ assignments: { type: Array, default: () => [] }, bookings: { type: Array, default: () => [] } });
const days = ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'];
function book(name, id) { router.post(route(name, id)); }
function cancel(id) { if (confirm('إلغاء الحجز؟')) router.delete(route('student.session-booking.cancel', id)); }
</script>
<template>
    <DashboardLayout><Head title="حجز المدرسين والمواعيد" /><div class="container-app px-4 py-8 space-y-8"><div><h1 class="text-3xl font-black text-surface-900 dark:text-white">اختيار المدرس والموعد</h1><p class="text-surface-500 mt-2">اختر مجموعة مناسبة أو احجز موعد برايفيت متاح.</p></div><section class="card p-6"><h2 class="font-bold text-lg mb-4">حجوزاتي الحالية</h2><div v-if="bookings.length" class="grid md:grid-cols-2 gap-3"><div v-for="booking in bookings" :key="booking.id" class="border rounded-xl p-4 flex justify-between"><div><b>{{ booking.group ? booking.group.assignment.subject.name : 'جلسة برايفيت' }}</b><p class="text-sm text-surface-500">{{ booking.group ? booking.group.assignment.grade_level.name + ' — ' + booking.group.name : new Date(booking.private_slot.starts_at).toLocaleString('ar-EG') }}</p></div><button class="text-red-500" @click="cancel(booking.id)">إلغاء</button></div></div><p v-else class="text-surface-500">لا توجد حجوزات حاليًا.</p></section><section v-for="item in assignments" :key="item.id" class="card p-6"><h2 class="font-bold text-lg">{{ item.subject.name }} — {{ item.grade_level.name }}</h2><p class="text-sm text-surface-500">المدرس: {{ item.teacher.name }}</p><div class="grid md:grid-cols-2 gap-3 mt-4"><div v-for="group in item.groups" :key="group.id" class="border rounded-xl p-4 flex justify-between"><div><b>{{ group.name }}</b><p class="text-sm text-surface-500">{{ days[group.day_of_week] }} | {{ group.start_time }} - {{ group.end_time }}</p><p class="text-xs text-primary-600">متاح {{ group.capacity - group.active_bookings_count }} من {{ group.capacity }}</p></div><button class="btn-primary btn-sm" :disabled="group.active_bookings_count >= group.capacity" @click="book('student.session-booking.group', group.id)">{{ group.active_bookings_count >= group.capacity ? 'مكتملة' : 'احجز المجموعة' }}</button></div><div v-for="slot in item.private_slots" :key="slot.id" class="border rounded-xl p-4 flex justify-between"><div><b>جلسة برايفيت</b><p class="text-sm text-surface-500">{{ new Date(slot.starts_at).toLocaleString('ar-EG') }}</p></div><button class="btn-primary btn-sm" @click="book('student.session-booking.private', slot.id)">احجز الموعد</button></div></div></section><p v-if="!assignments.length" class="card p-8 text-center text-surface-500">لا توجد مواعيد متاحة من المدرسين حتى الآن.</p></div></DashboardLayout>
</template>
